image: node:16.14.2
pipelines:
  branches:
    main:
      - step:
          name: Install npm modules and build production site with parcel
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy dist artifacts using sftp
          deployment: production
          script:
            - pipe: atlassian/sftp-deploy:0.5.12
              variables:
                USER: $USER
                SERVER: $SERVER
                PASSWORD: $PASSWORD # Optional.
                REMOTE_PATH: '/home/administrator/WEBROOT/archaeotype_v3/client'
                LOCAL_PATH: 'dist/' # Optional.
                # SSH_KEY: '<string>' # Optional.
                # EXTRA_ARGS: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.