image: node:16.14.2
pipelines:
  branches:
    main:
      - step:
          name: Install npm modules and build production site with parcel
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy dist artifacts using scp
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/home/administrator/WEBROOT/archaeotype_v3/client'
                LOCAL_PATH: 'dist/*'
